CREATE TABLE [dbo].[TemplateClause]
(
	[Id]   INT            IDENTITY (1, 1) NOT NULL,
	[TemplateId]   INT        NOT NULL,
	[StateId]   INT        NOT NULL,
    [Section] NVARCHAR (10)  NOT NULL,
	[TransactionTypeId]   INT        NOT NULL,
	[AgencyTypeId]   INT        NOT NULL,
    [Heading]      NVARCHAR (250)  NOT NULL,
	[SubHeading]      NVARCHAR (250)   NULL,
    [Sequence]     INT            DEFAULT ((1)) NOT NULL,
	[Clause]      NVARCHAR (Max)  NOT  NULL,
	[Conditions]      NVARCHAR (250)  NOT  NULL,
	[IsEditable] BIT   DEFAULT 0 NOT NULL,
    [IsDeleted]   BIT        NOT NULL DEFAULT 0,
	[Created] DATETIME       DEFAULT (getdate()) NOT NULL,
    [CreatedBy][varchar](128) NOT NULL DEFAULT (suser_sname()),
	[Modified]  DATETIME       DEFAULT (getdate()) NOT NULL,
    [ModifiedBy][varchar](128) NOT NULL DEFAULT (suser_sname()),
	CONSTRAINT [TemplateClause_PK] PRIMARY KEY NONCLUSTERED (Id ASC),
	CONSTRAINT [TemplateClause_Template_FK] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[Template] ([Id]),
	CONSTRAINT [TemplateClause_State_FK] FOREIGN KEY ([StateId]) REFERENCES [dbo].[trefStateType] ([Id]),
	CONSTRAINT [TemplateClause_TransactionType_FK] FOREIGN KEY ([TransactionTypeId]) REFERENCES [dbo].[trefTransactionType] ([Id]),
	CONSTRAINT [TemplateClause_AgencyType_FK] FOREIGN KEY ([AgencyTypeId]) REFERENCES [dbo].[trefAgencyType] ([Id]),
)
